[package]
name = "wc-demo"
version = "0.0.0"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"

[dependencies]
neon = { version = "0.0.10", path = "../neon" }
rayon = { git = "https://github.com/nikomatsakis/rayon" }
